### ISSUE TITLE
[Bug] Cannot use DPM with a Ledger

### ISSUE THREAD

**Issue by RiccardoM** [vaiainnovations/scripta#10]
## Description
I've setup my Desmos Profile Manager (DPM) to be used with my Ledger Nano X, but when I try confirming a transaction from Scripta I get the following error: 

> Error: Error: Can't sign, method direct is not supported from the wallet

### Screenshot
![screenshot-beta scripta network-2022 08 04-09_26_12](https://user-images.githubusercontent.com/9119016/182788906-1771d26b-e6b1-4e2c-bade-db3172350d01.png)

**Comment by g-luca** [comment]
Fixed with #4
