### ISSUE TITLE
[Bug] Refreshing profile with DPM closed does not work

### ISSUE THREAD

**Issue by RiccardoM** [vaiainnovations/scripta#11]
## Description
After having closed Desmos Profile Manager (DPM) on my device, if I refresh my profile page all the data disappear and cannot be loaded properly. No error is shown inside the console.  

### Steps to reproduce: 
1. Log with DPM 
2. Close DPM from the mobile device
3. Refresh the profile page 

### Screenshot

![screenshot-beta scripta network-2022 08 04-10_02_49](https://user-images.githubusercontent.com/9119016/182796023-b5047f07-c860-467a-8969-b0def8cccafb.png)

**Comment by g-luca** [comment]
Fixed with #4
