### ISSUE TITLE
Grant authorization is not working

### ISSUE THREAD

**Issue by lorenzomenegon** [vaiainnovations/scripta#14]
<img width="1317" alt="Screenshot 2023-01-19 alle 17 26 48" src="https://user-images.githubusercontent.com/106406454/213497820-69c4b717-617b-437f-879b-1a9ec976a0cc.png">

As you can see, you can no longer either post articles or grant authorization to sign transactions as an error occurs. Also, using the buttons to like or dislike a post does not work.

**Comment by g-luca** [comment]
Which authentication method did you use? Social (Web3Auth) ?

**Comment by lorenzomenegon** [comment]
Using Web3Auth with google right now
