### ISSUE TITLE
[Enhancement] Show more decimal places on balance

### ISSUE THREAD

**Issue by RiccardoM** [vaiainnovations/scripta#7]
## Description
Currently the Wallet only displays integer values, leaving out decimal places. At least this is what is happening with my balance which should be _0.0983 DARIC_ but is displayed as _0 DARIC_: 

![screenshot-beta scripta network-2022 08 03-11_35_21](https://user-images.githubusercontent.com/9119016/182578130-39099e3a-d3f7-430b-a17e-7574262f577e.png)

I think it would be more beneficial to always show 2 decimal values inside the balance, since even a wallet with as low as 0.01 DSM can correctly perform any kind of transaction.

**Comment by g-luca** [comment]
Fixed with #4
